# Numpy: Package for Multidimensional array
## Vector(1d)
## Matrix(2d or 1d)

## Create an array

In [1]:
import numpy as np    ### importing numpy alias as np

In [2]:
simple_list=[1,2,3]       ### creating list and then pass into the array
np.array(simple_list)

array([1, 2, 3])

In [3]:
arr=np.array([1,2,3])       ### directly passing the no. into the array will work as list due to [] brackets
arr

array([1, 2, 3])

In [4]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]     ### creating a matrix of 3 rows and 3 columns 
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(15,40)      ### Starting number is inclusive but end number is exclusive with step size 1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [6]:
np.arange(10,91,8)     ### Number starting from 10 to 90 with step size 8

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [7]:
np.zeros(6)    ### six zeros with float data type

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(6,dtype=int)   ### six zeros with integer data type specified

array([0, 0, 0, 0, 0, 0])

In [9]:
np.ones(5)    ### five ones with float data type

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5,dtype=int)   ### five ones with integer data type specified

array([1, 1, 1, 1, 1])

In [11]:
np.ones((2,5))    ### ones with 2 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,1,5)     ### number with linear spacing

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.eye(5)   ### Identity matrix of 5 rows and 5 columns with float data type

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.eye(5,dtype=int)    ### Identity matrix with integer data type

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
np.random.rand(2,4)   ### Random numbers between 0 and 1  in 2 rows and 4 coloumns

array([[0.61231686, 0.78443802, 0.61751724, 0.86407015],
       [0.76722375, 0.60466549, 0.26944181, 0.78552887]])

In [16]:
np.random.randn(2,4)     ### Random numbers with positive and negative in 2 rows and 4 coloumns

array([[-0.41533536,  0.43956419,  0.75491495,  1.4722599 ],
       [-0.71109275,  2.75135844,  0.51626566,  0.07097385]])

In [17]:
np.random.randint(1,5,4)  ### Random numbers with integer data type

array([3, 2, 3, 4])

In [18]:
sample_array=np.arange(2,20)    ### Numbers from 2 to 19
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
np.ones((3,4))    ### Ones in 3 rows and 4 coloumns in float data type

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
rand_array=np.random.randint(0,10,5)    ### 5 Random Numbers from 0 to 9 
rand_array

array([2, 4, 1, 7, 9])

In [21]:
sample_array.min()      ### Minimum number from the sample_array

2

In [22]:
sample_array.argmin()    ### Argument/Index of the minimum number from the sample_array

0

In [23]:
rand_array.argmin()      ### Argument/Index of minimum number from the rand_array

2

In [24]:
rand_array.max()     ###  Maximum number from the rand_array 

9

In [25]:
rand_array.argmax()     ### Argument/Index of the maximum numer from the rand_array

4

In [26]:
sample_array.argmax()     ###   Argument/Index of the maximum number from the sample_array

17

In [27]:
sample_array.dtype       ### Data type of sample array

dtype('int32')

In [28]:
a=np.eye(5)             ### Identity matrix 
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a=np.random.rand(2,3)      ### Random numbers in 2 rows and 3 coloumns
a

array([[0.97038312, 0.34042275, 0.3081426 ],
       [0.28417207, 0.79284117, 0.64968355]])

In [30]:
a.T                         ### Transpose Matrix

array([[0.97038312, 0.28417207],
       [0.34042275, 0.79284117],
       [0.3081426 , 0.64968355]])

In [31]:
sample_array=np.arange(10,28)             ### Numbers starting from 10 to 27
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [32]:
sample_array=sample_array.reshape(6,3)   ### Reshape the array according the rows and coloumns
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [33]:
sample_array=sample_array.reshape(3,4)      ### Array doesn't reshaped because no. of rows and coloumns does not match
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [34]:
sample_array[5]=100     ### 5th Index of sample_array becomes 100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [35]:
sample_array=np.arange(10,100)      ### Array from 10 to 99
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [36]:
sample_array[2:10]    ### Array from Index 2 to 9

array([12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
subset_sample_array=sample_array[0:7]   ### Array from Index 0 to 6
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [38]:
sample_array[1:5]=1001    ### Index 2 to 4 changes to 1001
sample_array

array([  10, 1001, 1001, 1001, 1001,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

# Two-Dimensional array

In [42]:
sample_matrix=np.array([[2,13,24,15],[65,4,2,15],[56,76,34,7]])    ### Two Dimensional array
sample_matrix

array([[ 2, 13, 24, 15],
       [65,  4,  2, 15],
       [56, 76, 34,  7]])

In [43]:
sample_matrix[2][2]      ### 2nd Row and 2nd Coloumn number

34

In [44]:
sample_matrix[1][3]     ### 1st Row and 3rd Coloumn number

15

In [45]:
sample_matrix[:,3]      ### All number from 3rd coloumn

array([15, 15,  7])

In [46]:
sample_matrix[2,2]       ### 2nd Row and 2nd Coloumn number

34

In [47]:
sample_matrix[1:3,2:4]    ### Number from 1st row to 3rd row and 2nd coloumn to 4th coloumn

array([[ 2, 15],
       [34,  7]])

In [49]:
sample_matrix[1:,2:]    ### Matrix from 1st Row and 2nd Coloumn onwards

array([[ 2, 15],
       [34,  7]])

In [50]:
sample_matrix[2]        ### 2nd Row Numbers

array([56, 76, 34,  7])

In [51]:
sample_array=np.arange(1,32)       ### Number from 1 to 31
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [53]:
sample_array+sample_array        ### Sum of the sample_array numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

In [54]:
np.exp(sample_array)       ### Exponential of the sample_array numbers

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13])

In [55]:
np.sqrt(sample_array)     ### Square root of the numbers of the sample_array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
       5.56776436])

In [56]:
np.log(sample_array)     ### Logarithimic of the numbers of the sample_array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 ])

In [57]:
np.max(sample_array)    ### Maximum number from the sample_array

31

In [58]:
np.min(sample_array)     ### Minimum number from the sample_array

1

In [59]:
np.argmax(sample_array)     ### Index of the maximum number from the sample_array

30

In [60]:
np.argmin(sample_array)      ### Index of the minimum number from the sample_array

0

In [61]:
np.square(sample_array)       ### Square of the numbers from the sample_array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900, 961], dtype=int32)

In [62]:
np.std(sample_array)      ### Standard Deviation of the numbers from the sample_array

8.94427190999916

In [63]:
np.var(sample_array)    ### Variance of the numbers from the sample_array

80.0

In [64]:
np.mean(sample_array)    ### Mean of the numbers from the sample_array

16.0

In [65]:
array=np.random.randn(3,4)       ### Positive and Negative Random numbers in 3 rows and 4 coloumns
array

array([[ 0.35273069,  0.36567587, -1.25243935,  1.35665446],
       [ 0.68260474,  0.07167964, -0.06350519,  0.76992222],
       [-0.1878323 , -0.27154816,  0.0060512 , -2.28117208]])

In [66]:
np.round(array,decimals=3)      ### Rounding off the numbers upto decimals  and Normal Distribution

array([[ 0.353,  0.366, -1.252,  1.357],
       [ 0.683,  0.072, -0.064,  0.77 ],
       [-0.188, -0.272,  0.006, -2.281]])

In [67]:
fruits=np.array(['apple','orange','mango','apple','orange'])    ###  fruits unique
np.unique(fruits)

array(['apple', 'mango', 'orange'], dtype='<U6')